In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\vijay\Downloads\2014-peak-hours-report-xlsx-a11y (1).xlsx")
print(df)

      DI  RTE   CO  PRE      PM     CS LEG  YR AM_DIR  AM_WAY_PHV  ...  \
0     12    1  ORA  NaN  22.500  623.0   O  14      S        2458  ...   
1     12    1  ORA  NaN  30.141  937.0   A  14      N        6550  ...   
2      7    1   LA  NaN  11.800  718.0   A  14      N        2407  ...   
3      7    1   LA  NaN  27.100  425.0   O  14      N        4754  ...   
4      7    1   LA  NaN  35.170  237.0   O  14      S        3321  ...   
...   ..  ...  ...  ...     ...    ...  ..  ..    ...         ...  ...   
5831  11  805   SD  NaN  24.440  683.0   X  17      N        8892  ...   
5832  11  805   SD  NaN  28.502  930.0   B  17      S        7327  ...   
5833  11  905   SD  NaN   3.207  932.0   A  17      W        2533  ...   
5834  11  905   SD  NaN   5.164  942.0   A  17      E        4089  ...   
5835  11  905   SD    R  11.366  127.0   A  17      W        1531  ...   

      AM_DAY  AM_MONTH  PM_DIR  PM_WAY_PHV PM_K_FACTOR_AMT PM_D_FACTOR_AMT  \
0        WED       SEP       N   

In [3]:
df_test = pd.read_excel(r"C:\Users\vijay\Downloads\2018-peak-hours.xlsx")
df_test

DI  RTE   CO  PRE      PM     CS LEG  YR AM_DIR  AM_WAY_PHV  ...  \
0     12    1  ORA  NaN  22.500  623.0   O  18      S        2531  ...   
1     12    1  ORA  NaN  30.141  937.0   A  16      N       14488  ...   
2      7    1   LA  NaN  27.100  425.0   O  17      N        4363  ...   
3      7    1   LA  NaN  40.769  720.0   A  16      N        2106  ...   
4      7    1   LA  NaN  48.171   45.0   A  16      N        1440  ...   
...   ..  ...  ...  ...     ...    ...  ..  ..    ...         ...  ...   
4023  11  805   SD  NaN  28.502  930.0   B  20      S        5338  ...   
4024  11  805   SD  NaN  28.874  947.0   B  20      N        5304  ...   
4025  11  905   SD  NaN   3.207  932.0   A  20      E        2610  ...   
4026  11  905   SD  NaN   5.164  942.0   A  20      E        8473  ...   
4027  11  905   SD    R   9.778  128.0   B  20      E        4627  ...   

      AM_DAY  AM_MONTH  PM_DIR  PM_WAY_PHV PM_K_FACTOR_AMT PM_D_FACTOR-AMT  \
0        WED       JAN       N        2539           10.02           70.10   
1        FRI       JUN       S        3012            7.82           75.49   
2        TUE       OCT       N        3980            7.66           62.80   
3        MON       FEB       N        2742            9.64           58.20   
4        SAT       AUG       S        1497            9.91           51.27   
...      ...       ...     ...         ...             ...             ...   
4023     TUE       NOV       S        5594            6.33           61.36   
4024     THU       DEC       N        6806            8.53           67.99   
4025     TUE       FEB       E        2906           10.72           53.97   
4026     THU       OCT       E        8391           13.84           82.02   
4027     WED       JUL       E        5365           13.72           67.89   

     PM_KD_FACTOR  PM_HOUR  PM_DAY  PM_MONTH  
0            7.02       17     THU       APR  
1            5.90       19     WED       OCT  
2            4.81       17     TUE       JUN  
3            5.61       17     TUE       JAN  
4            5.08       15     FRI       MAR  
...           ...      ...     ...       ...  
4023         3.88       15     THU       JUL  
4024         5.80       16     THU       JAN  
4025         5.79       15     WED       DEC  
4026        11.35       19     FRI       NOV  
4027         9.32       14     FRI       OCT  

[4028 rows x 24 columns]

In [4]:
df.drop(["PRE","AM_DIR","AM_WAY_PHV","AM_K_FACTOR_AMT","AM_D_FACTOR_AMT","AM_KD_FACTOR","AM_HOUR","AM_DAY","AM_MONTH"],inplace = True,axis = 1)
df_test.drop(["PRE","AM_DIR","AM_WAY_PHV","AM_K_FACTOR_AMT","AM_D_FACTOR_AMT","AM_KD_FACTOR","AM_HOUR","AM_DAY","AM_MONTH"],inplace = True,axis = 1)

In [5]:
df["PM_WAY_PHV"]

0       2474
1       2454
2       2161
3       4098
4       2696
        ... 
5831    9221
5832    6906
5833    2872
5834    4200
5835    1748
Name: PM_WAY_PHV, Length: 5836, dtype: int64

In [6]:
Y_train = df["PM_WAY_PHV"]
Y_test = df_test["PM_WAY_PHV"]
df.drop("PM_WAY_PHV",inplace = True,axis = 1)
df_test.drop("PM_WAY_PHV",inplace = True,axis = 1)
X_train = df
X_test = df_test
print(X_test)

      DI  RTE   CO      PM     CS LEG  YR PM_DIR  PM_K_FACTOR_AMT  \
0     12    1  ORA  22.500  623.0   O  18      N            10.02   
1     12    1  ORA  30.141  937.0   A  16      S             7.82   
2      7    1   LA  27.100  425.0   O  17      N             7.66   
3      7    1   LA  40.769  720.0   A  16      N             9.64   
4      7    1   LA  48.171   45.0   A  16      S             9.91   
...   ..  ...  ...     ...    ...  ..  ..    ...              ...   
4023  11  805   SD  28.502  930.0   B  20      S             6.33   
4024  11  805   SD  28.874  947.0   B  20      N             8.53   
4025  11  905   SD   3.207  932.0   A  20      E            10.72   
4026  11  905   SD   5.164  942.0   A  20      E            13.84   
4027  11  905   SD   9.778  128.0   B  20      E            13.72   

      PM_D_FACTOR-AMT  PM_KD_FACTOR  PM_HOUR PM_DAY PM_MONTH  
0               70.10          7.02       17    THU      APR  
1               75.49          5.90       19 

In [7]:
print(X_train.shape)
print(X_test.shape)

(5836, 14)
(4028, 14)


In [8]:
df_test.describe()

DI          RTE           PM           CS           YR  \
count  4028.000000  4028.000000  4028.000000  4000.000000  4028.000000   
mean      6.081678   116.960775    23.567263   472.519000    18.494042   
std       3.186299   124.126906    24.350808   318.284253     1.173634   
min       1.000000     1.000000     0.000000     1.000000    16.000000   
25%       3.000000    41.000000     6.825000   177.000000    18.000000   
50%       6.000000    89.000000    16.700000   418.000000    19.000000   
75%       9.000000   160.000000    31.238000   773.000000    19.000000   
max      12.000000   905.000000   156.492000   999.000000    20.000000   

       PM_K_FACTOR_AMT  PM_D_FACTOR-AMT  PM_KD_FACTOR      PM_HOUR  
count      4028.000000      4028.000000   4028.000000  4028.000000  
mean         10.903220        61.783257      6.867761    15.530536  
std           4.647799         8.795034      3.951662     1.505329  
min           2.490000        50.010000      1.530000     0.000000  
25%           8.570000        55.170000      5.000000    15.000000  
50%           9.830000        60.090000      5.920000    16.000000  
75%          11.720000        65.750000      7.582500    16.000000  
max          86.380000        99.880000     82.410000    23.000000

In [9]:
df.CS.fillna(df.CS.mean(),inplace = True)
df_test.CS.fillna(df_test.CS.mean(),inplace = True)
df_test.describe()

DI          RTE           PM           CS           YR  \
count  4028.000000  4028.000000  4028.000000  4028.000000  4028.000000   
mean      6.081678   116.960775    23.567263   472.519000    18.494042   
std       3.186299   124.126906    24.350808   317.175797     1.173634   
min       1.000000     1.000000     0.000000     1.000000    16.000000   
25%       3.000000    41.000000     6.825000   179.000000    18.000000   
50%       6.000000    89.000000    16.700000   422.500000    19.000000   
75%       9.000000   160.000000    31.238000   771.000000    19.000000   
max      12.000000   905.000000   156.492000   999.000000    20.000000   

       PM_K_FACTOR_AMT  PM_D_FACTOR-AMT  PM_KD_FACTOR      PM_HOUR  
count      4028.000000      4028.000000   4028.000000  4028.000000  
mean         10.903220        61.783257      6.867761    15.530536  
std           4.647799         8.795034      3.951662     1.505329  
min           2.490000        50.010000      1.530000     0.000000  
25%           8.570000        55.170000      5.000000    15.000000  
50%           9.830000        60.090000      5.920000    16.000000  
75%          11.720000        65.750000      7.582500    16.000000  
max          86.380000        99.880000     82.410000    23.000000

In [10]:
dir_mapping = {
    "N": 1,
    "S": 2,
    "E": 3,
    "W": 4
    }

df["PM_DIR"] = df["PM_DIR"].map(dir_mapping)
df_test["PM_DIR"] = df_test["PM_DIR"].map(dir_mapping)

In [11]:
day_mapping = {
    "SUN" : 1,
    "MON" : 2,
    "TUE" : 3,
    "WED" : 4,
    "THU" : 5,
    "FRI" : 6,
    "SAT" : 7
}

df["PM_DAY"] = df["PM_DAY"].map(day_mapping)
df_test["PM_DAY"] = df_test["PM_DAY"].map(day_mapping)

month_mapping = {
    
    "JAN": 1,
    "FEB": 2,
    "MAR": 3,
    "APR": 4,
    "MAY": 5,
    "JUN": 6,
    "JUL": 7,
    "AUG": 8,
    "SEP": 9,
    "OCT": 10,
    "NOV": 11,
    "DEC": 12
}

df["PM_MONTH"] = df["PM_MONTH"].map(month_mapping)
df_test["PM_MONTH"] = df_test["PM_MONTH"].map(month_mapping)
df_test

DI  RTE   CO      PM     CS LEG  YR  PM_DIR  PM_K_FACTOR_AMT  \
0     12    1  ORA  22.500  623.0   O  18       1            10.02   
1     12    1  ORA  30.141  937.0   A  16       2             7.82   
2      7    1   LA  27.100  425.0   O  17       1             7.66   
3      7    1   LA  40.769  720.0   A  16       1             9.64   
4      7    1   LA  48.171   45.0   A  16       2             9.91   
...   ..  ...  ...     ...    ...  ..  ..     ...              ...   
4023  11  805   SD  28.502  930.0   B  20       2             6.33   
4024  11  805   SD  28.874  947.0   B  20       1             8.53   
4025  11  905   SD   3.207  932.0   A  20       3            10.72   
4026  11  905   SD   5.164  942.0   A  20       3            13.84   
4027  11  905   SD   9.778  128.0   B  20       3            13.72   

      PM_D_FACTOR-AMT  PM_KD_FACTOR  PM_HOUR  PM_DAY  PM_MONTH  
0               70.10          7.02       17       5         4  
1               75.49          5.90       19       4        10  
2               62.80          4.81       17       3         6  
3               58.20          5.61       17       3         1  
4               51.27          5.08       15       6         3  
...               ...           ...      ...     ...       ...  
4023            61.36          3.88       15       5         7  
4024            67.99          5.80       16       5         1  
4025            53.97          5.79       15       4        12  
4026            82.02         11.35       19       6        11  
4027            67.89          9.32       14       6        10  

[4028 rows x 14 columns]

In [12]:
cl = set(df_test["CO"]) - set(df["CO"])
cl

set()

In [13]:
columns = set(df["CO"])
ds = {'ALA':1,
 'ALP':2,
 'AMA':3,
 'BUT':4,
 'CAL':5,
 'CC':6,
 'COL':7,
 'DN':8,
 'ED':9,
 'FRE':10,
 'GLE':11,
 'HUM':12,
 'IMP':13,
 'INY':14,
 'KER':15,
 'KIN':16,
 'LA':17,
 'LAK':18,
 'LAS':19,
 'MAD':20,
 'MEN':21,
 'MER':22,
 'MNO':23,
 'MOD':24,
 'MON':25,
 'MPA':26,
 'MRN':27,
 'NAP':28,
 'NEV':29,
 'ORA':30,
 'PLA':31,
 'PLU':32,
 'RIV':33,
 'SAC':34,
 'SB':35,
 'SBD':36,
 'SBT':37,
 'SCL':38,
 'SCR':39,
 'SD':40,
 'SF':41,
 'SHA':42,
 'SIE':43,
 'SIS':44,
 'SJ':45,
 'SLO':46,
 'SM':47,
 'SOL':48,
 'SON':49,
 'STA':50,
 'SUT':51,
 'TEH':52,
 'TRI':53,
 'TUL':54,
 'TUO':55,
 'VEN':56,
 'YOL':57,
 'YUB':58
     }
df["CO"] = df["CO"].map(ds)
df_test["CO"] = df_test["CO"].map(ds)
df

data = {
    "A": 1,
    "B": 2,
    "O": 3,
    "X": 4
    }
df["LEG"] = df["LEG"].map(data)
df_test["LEG"] = df_test["LEG"].map(data)

df_test

DI  RTE  CO      PM     CS  LEG  YR  PM_DIR  PM_K_FACTOR_AMT  \
0     12    1  30  22.500  623.0    3  18       1            10.02   
1     12    1  30  30.141  937.0    1  16       2             7.82   
2      7    1  17  27.100  425.0    3  17       1             7.66   
3      7    1  17  40.769  720.0    1  16       1             9.64   
4      7    1  17  48.171   45.0    1  16       2             9.91   
...   ..  ...  ..     ...    ...  ...  ..     ...              ...   
4023  11  805  40  28.502  930.0    2  20       2             6.33   
4024  11  805  40  28.874  947.0    2  20       1             8.53   
4025  11  905  40   3.207  932.0    1  20       3            10.72   
4026  11  905  40   5.164  942.0    1  20       3            13.84   
4027  11  905  40   9.778  128.0    2  20       3            13.72   

      PM_D_FACTOR-AMT  PM_KD_FACTOR  PM_HOUR  PM_DAY  PM_MONTH  
0               70.10          7.02       17       5         4  
1               75.49          5.90       19       4        10  
2               62.80          4.81       17       3         6  
3               58.20          5.61       17       3         1  
4               51.27          5.08       15       6         3  
...               ...           ...      ...     ...       ...  
4023            61.36          3.88       15       5         7  
4024            67.99          5.80       16       5         1  
4025            53.97          5.79       15       4        12  
4026            82.02         11.35       19       6        11  
4027            67.89          9.32       14       6        10  

[4028 rows x 14 columns]

In [14]:
df.describe()

DI          RTE           CO           PM           CS  \
count  5836.000000  5836.000000  5836.000000  5836.000000  5836.000000   
mean      5.979267   121.570425    29.695853    22.450558   438.296639   
std       3.102767   140.357017    15.488178    23.214678   314.694317   
min       1.000000     1.000000     1.000000     0.000000     1.000000   
25%       3.000000    36.000000    15.000000     6.656000   156.000000   
50%       6.000000    89.000000    31.000000    15.906000   341.500000   
75%       8.000000   154.000000    42.000000    30.011000   722.000000   
max      12.000000   905.000000    58.000000   156.492000   999.000000   

               LEG           YR       PM_DIR  PM_K_FACTOR_AMT  \
count  5836.000000  5836.000000  5836.000000      5836.000000   
mean      1.656100    14.947910     2.326422        10.612887   
std       0.693067     1.325523     1.066685         4.337897   
min       1.000000    12.000000     1.000000         4.850000   
25%       1.000000    14.000000     1.000000         8.410000   
50%       2.000000    15.000000     2.000000         9.660000   
75%       2.000000    16.000000     3.000000        11.400000   
max       4.000000    17.000000     4.000000        82.520000   

       PM_D_FACTOR_AMT  PM_KD_FACTOR      PM_HOUR       PM_DAY     PM_MONTH  
count      5836.000000   5836.000000  5836.000000  5836.000000  5836.000000  
mean         61.548874      6.627164    15.706306     4.192255     6.703735  
std           8.426262      3.349832     1.472548     1.905671     3.142728  
min          50.010000      2.680000     0.000000     1.000000     1.000000  
25%          55.210000      4.920000    15.000000     3.000000     4.000000  
50%          59.710000      5.800000    16.000000     5.000000     7.000000  
75%          65.835000      7.310000    17.000000     6.000000     9.000000  
max          99.880000     54.270000    23.000000     7.000000    12.000000

In [15]:
#from sklearn.decomposition import PCA
  
#pca = PCA(n_components = 10)
  
#X_pca = pca.fit_transform(df)
#X_pca.shape

In [16]:
from sklearn.tree import DecisionTreeRegressor

clf = DecisionTreeRegressor()
clf.fit(X_train,Y_train)

DecisionTreeRegressor()

In [17]:
Y_train_pred = clf.predict(X_train).reshape(-1,1)
Y_test_pred = clf.predict(X_test).reshape(-1,1)

In [18]:
from sklearn.metrics import confusion_matrix
train = confusion_matrix(Y_train,Y_train_pred)
test = confusion_matrix(Y_test,Y_test_pred)

print(train)

[[3 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [19]:
from sklearn import metrics
print("Accuracy:",clf.score(X_test, Y_test))

Accuracy: 0.6229497844980335


In [20]:
from sklearn.neighbors import KNeighborsRegressor
clf = KNeighborsRegressor(n_neighbors = 7)
clf.fit(X_train, Y_train)
clf.score(X_test,Y_test)

0.5875448889368531

In [21]:
from sklearn.metrics import accuracy_score
predict_output = clf.predict(X_test)
predict_output

array([2452.42857143, 6811.42857143, 5550.28571429, ..., 3292.71428571,
       3444.        , 1866.14285714])